### PR TITLE
Feature/make time range picker public

### PR DESCRIPTION
**Pull request by JanezStupar**
I made a couple of changes to the picker so it can be used as standalone widget, without using the dialog.
Added a flag to not display a button bar.
Changed visibility of builder functions so that picker can be extended and behavior overridden in client apps.

### CODE REVIEW

**Comment by Chris1234567899** [comment]
I'm generally ok with this, just one thing I noticed:

in the last commit you added the widget in the example home page. However it does not scale well in landscape mode. I think it's just a minor thing because of the parent widget (Expanded + Column).  

Once this is fixed I'll merge it.

**Comment by JanezStupar** [comment]
@Chris1234567899 there you. Let me know if this is satisfactory.

**Comment by Chris1234567899** [comment]
Had to switch to a custom gesture detector to fix the conflict with scroll when in a scrollview. Should work now

**Comment by JanezStupar** [comment]
Thats perfect. Much better than what I attempted in the other PR.

**Comment by Chris1234567899** [comment]
Thanks, I just published the changes under 1.1.0

**Pull request merged**
